---
version: "1.0"
 
services:
  web:
    image: shreyashsingh1/dopam:latest
    expose:
      - port: 5000
        as: 5000
        to:
          - global: true
    env:
      - TEST=test

    command: ["python", "application.py"]
  
profiles:
  name: hello-world
  duration: 640min
  tier:
    - community
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 16Gi
        storage:
          size: 16Gi

        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: t1000
  placement:
    westcoast:
      attributes:
        region: us-central
      pricing:
        web:
          denom: USDT
          amount: 500000
 
deployment:
  web:
    westcoast:
      profile: web
      count: 1
      